### ISSUE TITLE
Undeclared tidyverse dependency

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/weathercan#76]
I asked @jeroen why `weathercan` didn't have it's own spiffy https://docs.ropensci.org/ webpage as I was updating links in the documentation of `GSODR` for a new CRAN release. 

Apparently you have an undeclared dependency, `tidyverse` see the log here for more: https://dev.ropensci.org/job/weathercan/35/console

**Comment by jeroen** [comment]
If you add `Suggests: tidyverse` to your package description, it should fix the site!

**Comment by adamhsparks** [comment]
Yes, I thought about a PR, but wasn't sure if it was desirable to keep `tidyverse` in Suggests seeing some past issues it looked like it was being removed from `weathercan` perhaps.

**Comment by jeroen** [comment]
If tidyverse is used in vignettes, it has to be in Suggests to pass CMD check as well...

**Comment by steffilazerte** [comment]
@jeroen, we're still having a problem with one of the articles not compiling on the jenkins server, due to missing packages. Currently it's a package that I have no idea where it comes from (seems to be a `ggplot2` dependency?).

I could just add that package to the suggest, but the problem I have is that there is one quite advanced article (i.e. not a vignette, but an article for the pkgdown website) that requires special packages that `weathercan` doesn't depend on. The easy solution is to add them to the `weathercan` suggests field, but I'm reluctant to do that when they're not at all required for `weathercan` itself. 

Is there a way to specify that these packages need to be installed for the compilation of the documentation on the ropensci/jenkins server? i.e. some sort of yaml file I can add? or a way to customized the build itself?

**Comment by jeroen** [comment]
OK fair enough. I usually put all stuff in suggests, but I can imagine you don't like that. I opened an issue here: https://github.com/ropensci/docs/issues/9

**Comment by steffilazerte** [comment]
@jeroen  Thanks for adding the option for `extra_packages` in the pkgdown yaml, that makes it much easier. I noticed that you've been making changes to the weathercan pkgdown yaml. I assume this was to add in the extra dependencies and change the theme to match ROpenSci? I'm a bit sad to lose my red-themed (i.e. weathercan-themed) site, but it makes sense to have unified ROpenSci theme.

Could you clarify what the difference is between http://ropensci.github.io/weathercan and https://docs.ropensci.org/weathercan/? I'm just wondering how important it is that I update all the links pointing to the old site (i.e. on printed material, new material will have the new site).

Other than that I think we're done with this issue.

**Comment by jeroen** [comment]
We no longer use the GitHub.io domain. This now redirects to docs.ropenci.org.

**Comment by steffilazerte** [comment]
Well that makes it easier! Thanks
